# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=20)),
                ('playerRights', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=20)),
                ('playerPass', models.CharField(max_length=25)),
                ('playerRights', models.IntegerField(default=0)),
                ('blackMarks', models.IntegerField(default=0)),
                ('timePlayed', models.BigIntegerField(default=0)),
                ('ipAddress', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
