# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 00:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banID', models.IntegerField(default=0)),
                ('appealField', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannedPlayer', models.CharField(max_length=20)),
                ('bannedBy', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('canAppeal', models.BooleanField(default=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerRights', models.IntegerField(blank=True, default=0)),
                ('blackMarks', models.IntegerField(blank=True, default=0)),
                ('timePlayed', models.BigIntegerField(blank=True, default=0)),
                ('ipAddress', models.GenericIPAddressField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=20)),
                ('reporter', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
